# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: normal_camera.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'normal_camera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13normal_camera.proto\x12\rnormal_camera\x1a\x1bgoogle/protobuf/empty.proto\"<\n\x16ObjectDetectionRequest\x12\x11\n\tcamera_id\x18\x01 \x01(\r\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32`\n\x0cNormalCamera\x12P\n\x0fObjectDetection\x12%.normal_camera.ObjectDetectionRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'normal_camera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECTDETECTIONREQUEST']._serialized_start=67
  _globals['_OBJECTDETECTIONREQUEST']._serialized_end=127
  _globals['_NORMALCAMERA']._serialized_start=129
  _globals['_NORMALCAMERA']._serialized_end=225
# @@protoc_insertion_point(module_scope)
