# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: depth_camera.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'depth_camera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x65pth_camera.proto\"\x18\n\x16ObjectDetectionRequest\"*\n\x17ObjectDetectionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x0e\n\x0c\x44\x65pthRequest\"Z\n\rDepthResponse\x12\x14\n\x0c\x64\x65pth_values\x18\x01 \x01(\x02\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x0f\n\x07x_coord\x18\x03 \x01(\x11\x12\x0f\n\x07y_coord\x18\x04 \x01(\x11\x32\x83\x01\n\x0b\x44\x65pthCamera\x12\x44\n\x0fObjectDetection\x12\x17.ObjectDetectionRequest\x1a\x18.ObjectDetectionResponse\x12.\n\rGetDepthImage\x12\r.DepthRequest\x1a\x0e.DepthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'depth_camera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECTDETECTIONREQUEST']._serialized_start=22
  _globals['_OBJECTDETECTIONREQUEST']._serialized_end=46
  _globals['_OBJECTDETECTIONRESPONSE']._serialized_start=48
  _globals['_OBJECTDETECTIONRESPONSE']._serialized_end=90
  _globals['_DEPTHREQUEST']._serialized_start=92
  _globals['_DEPTHREQUEST']._serialized_end=106
  _globals['_DEPTHRESPONSE']._serialized_start=108
  _globals['_DEPTHRESPONSE']._serialized_end=198
  _globals['_DEPTHCAMERA']._serialized_start=201
  _globals['_DEPTHCAMERA']._serialized_end=332
# @@protoc_insertion_point(module_scope)
