# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import depth_camera_pb2 as depth__camera__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in depth_camera_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DepthCameraStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObjectDetection = channel.unary_unary(
                '/DepthCamera/ObjectDetection',
                request_serializer=depth__camera__pb2.ObjectDetectionRequest.SerializeToString,
                response_deserializer=depth__camera__pb2.ObjectDetectionResponse.FromString,
                _registered_method=True)
        self.GetDepthImage = channel.unary_unary(
                '/DepthCamera/GetDepthImage',
                request_serializer=depth__camera__pb2.DepthRequest.SerializeToString,
                response_deserializer=depth__camera__pb2.DepthResponse.FromString,
                _registered_method=True)


class DepthCameraServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ObjectDetection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDepthImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DepthCameraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObjectDetection': grpc.unary_unary_rpc_method_handler(
                    servicer.ObjectDetection,
                    request_deserializer=depth__camera__pb2.ObjectDetectionRequest.FromString,
                    response_serializer=depth__camera__pb2.ObjectDetectionResponse.SerializeToString,
            ),
            'GetDepthImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDepthImage,
                    request_deserializer=depth__camera__pb2.DepthRequest.FromString,
                    response_serializer=depth__camera__pb2.DepthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DepthCamera', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DepthCamera', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DepthCamera(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ObjectDetection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DepthCamera/ObjectDetection',
            depth__camera__pb2.ObjectDetectionRequest.SerializeToString,
            depth__camera__pb2.ObjectDetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDepthImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DepthCamera/GetDepthImage',
            depth__camera__pb2.DepthRequest.SerializeToString,
            depth__camera__pb2.DepthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
