# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: depth_camera.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'depth_camera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x65pth_camera.proto\x12\x0c\x64\x65pth_camera\x1a\x1bgoogle/protobuf/empty.proto\"F\n\x0c\x44\x65pthRequest\x12\x14\n\x0c\x64\x65pth_values\x18\x01 \x01(\x02\x12\x0f\n\x07x_coord\x18\x02 \x01(\r\x12\x0f\n\x07y_coord\x18\x03 \x01(\r2S\n\x0b\x44\x65pthCamera\x12\x44\n\x0eSendDepthImage\x12\x1a.depth_camera.DepthRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'depth_camera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEPTHREQUEST']._serialized_start=65
  _globals['_DEPTHREQUEST']._serialized_end=135
  _globals['_DEPTHCAMERA']._serialized_start=137
  _globals['_DEPTHCAMERA']._serialized_end=220
# @@protoc_insertion_point(module_scope)
